
// @ts-ignore
declare const openapi = {
    paths: {
        '/follows/count': { get: [Object] },
        '/follows/{id}': { put: [Object], patch: [Object], get: [Object], delete: [Object] },
        '/follows': { post: [Object], patch: [Object], get: [Object] },
        '/pages/count': { get: [Object] },
        '/pages/{id}': { put: [Object], patch: [Object], get: [Object], delete: [Object] },
        '/pages': { post: [Object], patch: [Object], get: [Object] },
        '/people/bytecode-followers-greater-than': { get: [Object] },
        '/people/count': { get: [Object] },
        '/people/followers': { get: [Object] },
        '/people/many': { post: [Object] },
        '/people/promise-followers-greater-than': { get: [Object] },
        '/people/save/{id}': { put: [Object] },
        '/people/{id}': { put: [Object], patch: [Object], get: [Object], delete: [Object] },
        '/people': { post: [Object], patch: [Object], get: [Object] },
        '/ping': { get: [Object] },
        '/post-owners/count': { get: [Object] },
        '/post-owners/{id}': { put: [Object], patch: [Object], get: [Object], delete: [Object] },
        '/post-owners': { post: [Object], patch: [Object], get: [Object] },
        '/posts/by-user/{id}': { get: [Object] },
        '/posts/count': { get: [Object] },
        '/posts/related': { post: [Object] },
        '/posts/{id}': { put: [Object], patch: [Object], get: [Object], delete: [Object] },
        '/posts': { post: [Object], patch: [Object], get: [Object] },
        '/test-helper/cleanup-db': { get: [Object] }
      },
      servers: [ { url: 'http://127.0.0.1:3001' } ],
      components: {
        schemas: {
          Follow: [Object],
          NewFollow: [Object],
          FollowWithRelations: [Object],
          FollowPartial: [Object],
          Page: [Object],
          NewPage: [Object],
          PageWithRelations: [Object],
          PagePartial: [Object],
          People: [Object],
          NewPeople: [Object],
          BatchPeople: [Object],
          PeopleWithRelations: [Object],
          PeoplePartial: [Object],
          PostOwner: [Object],
          NewPostOwner: [Object],
          PostOwnerWithRelations: [Object],
          PostOwnerPartial: [Object],
          Post: [Object],
          NewPost: [Object],
          PostWithRelations: [Object],
          PostPartial: [Object],
          NewPosts: [Object],
          'loopback.Count': [Object],
          'Follow.Filter': [Object],
          'Follow.Filter1': [Object],
          'Page.Filter': [Object],
          'Page.Filter1': [Object],
          'People.Filter': [Object],
          'People.Filter1': [Object],
          PingResponse: [Object],
          'PostOwner.Filter': [Object],
          'PostOwner.Filter1': [Object],
          'Post.Filter': [Object],
          'Post.Filter1': [Object]
        }
      }
}